// Static editorial content for the journal, help and legal pages.
// Demo data — hard-coded so the new pages don't need a CMS.

export const JOURNAL_POSTS = [
  {
    slug: 'monsoon-coorg',
    title: 'Where the monsoon goes to write',
    dest: 'Coorg',
    read: '6 min',
    hue: 'forest',
    author: 'Riya Bhandari',
    date: 'May 2026',
    excerpt: 'A week in the Western Ghats when the rains move sideways and the coffee tastes greener.',
    body: [
      'The road to Madikeri leaves the Mysore plateau the way a sentence leaves the mind — slowly at first, then in a rush, then in a long unbroken curve. We left at five in the morning and the air was the temperature of held breath. By eight we were in the hills.',
      'The Western Ghats have two seasons that matter: dry, when the slopes burn copper, and monsoon, when everything becomes a verb. The coffee plants drink. The slopes pour. The forest *moves* — not just the leaves, the whole understory shifting an inch a day under the weight of the water.',
      'House of Cardamom is a plantation bungalow about twelve kilometres from anywhere. It was built in 1934 by a Scottish planter who wanted, badly, to be in Edinburgh. The result is an architectural compromise: thick walls, peaked roof, deep verandahs, a fireplace in every room. The compromise works. In monsoon you can sit on the verandah with a cup of estate-grown coffee and watch the rain do its theatre across the cardamom canopy.',
      'We did this for six mornings. We read books. We watched the malabar gliding lizard — actually a lizard, actually gliding — leave a tree near the kitchen at 9:14 on Tuesday and arrive at a tree near the dining room at 9:14:02. Brief. Decisive. Forgotten by every species except us.',
      'On the seventh morning the rain stopped. The slopes steamed. A pair of Malabar squirrels — a metre long including tail, the colour of dried blood and turmeric — moved up a jackfruit tree in two unhurried bounds. We packed.',
      'We will come back in the next monsoon.',
    ],
  },
  {
    slug: 'konkan-coast',
    title: 'A field guide to the Konkan coast',
    dest: 'Goa',
    read: '11 min',
    hue: 'ocean',
    author: 'Marcus Lee',
    date: 'April 2026',
    excerpt: 'Eleven minutes on choosing a beach, a bakery, a tide chart, and a hammock — in that order.',
    body: [
      'Most people, told they are going to "Goa," picture a single beach. There is no single beach. The Konkan strip is two hundred kilometres of varied coastline, broken into roughly thirty named beaches, each with its own posture toward visitors. A beach in North Goa in February is not the same as a beach in South Goa in August. This guide tries to make that less confusing.',
      '**Start with North.** Mandrem and Ashvem are slow and adult; Anjuna and Vagator are loud and young; Morjim is for the families and the sea turtles. If you can only see one beach in North Goa, see Mandrem at low tide on a weekday morning. The estuary cuts the sand into ribbons; you wade across to a sandbar where nobody is.',
      '**Don\'t skip the interior.** The villages five kilometres inland from any of the famous beaches — Assagao, Saligao, Aldona — are where the architecture lives. Indo-Portuguese houses, brick-red and gold-cream, with deep loggias and ceramic-tiled roofs. The villas are mostly hotels now, which is mostly a good thing.',
      '**Eat where the bakers are.** Every Goan village has a *poder* — the bread-man — who delivers fresh pao at six in the morning on a bicycle. Follow him. Wherever he stops longest, that is the bakery that supplies the village. Buy three things: the pao, the brun, and the kankon. Eat them in that order.',
      '**Watch the tide chart.** Sunset at half-tide is the photograph; sunrise at low tide is the long, quiet walk you will remember. The chart costs nothing — your hotel will print it for you.',
      '**A note on the South.** South Goa is quieter, the beaches are wider, and the food is slightly better. Trade-off: there is less to do. Decide which you want before you book.',
      'The Konkan coast rewards specificity. Don\'t go to "a beach." Go to *that* beach, on *that* tide, with *that* bakery\'s bread in your bag.',
    ],
  },
  {
    slug: 'rajasthan-rooms',
    title: 'Seven rooms with a view in Rajasthan',
    dest: 'Udaipur',
    read: '8 min',
    hue: 'sand',
    author: 'Anaya Mehra',
    date: 'March 2026',
    excerpt: 'Lake suites, fort cells, palace balconies. A short list of rooms that earn their description.',
    body: [
      'Rajasthan has a problem with the word *view*. Every property has one. The marketing copy says so. The booking sites confirm. By the third week of a fact-checking trip last winter I had stopped believing the word entirely.',
      'These seven rooms restored my belief. They are listed in the order I would book them if I were going back next month.',
      '**1. The Marigold House — Heritage Suite, Udaipur.** The lake is *there*. Twelve metres from the bed, framed by jharokhas that are themselves four hundred years old. At sunset the light passes through the carved sandstone and falls on the floor in slow rectangles.',
      '**2. Aravali Retreat — Stargazer Suite, Kumbhalgarh.** Modernist, low-slung, set into a pine ridge three hours from Udaipur. The observatory deck is private to the suite. On a clear winter night you can read by the Milky Way.',
      '**3. Silk Route Inn — Rooftop Suite, Jaisalmer.** Inside the living fort. The room itself is small and brass-trimmed; the roof is the whole point. The Thar desert begins at the horizon and continues, undisturbed, into Pakistan.',
      '**4. Devi Garh — Aravalli Suite, Delwara.** Eighteenth-century palace, restored with such restraint that the new joinery is indistinguishable from the old. The view is of the village below and the goat-paths that connect it.',
      '**5. Suján Rajmahal — Mughal Suite, Jaipur.** A working royal palace where the cushions still pretend nothing has changed since 1834. The view is of the courtyard, which is the point.',
      '**6. Khem Villas — Tented Suite, Ranthambore.** A canvas room with the door open onto the buffer zone of the tiger reserve. The view changes with the wildlife. Last visit: a sambar deer at 4 am.',
      '**7. Sardar Samand Lake Palace — North Wing, Pali.** The bath has a window onto the lake. That is all you need to know.',
      'Book early. Most of these seven have eight rooms or fewer.',
    ],
  },
  {
    slug: 'auroville-architecture',
    title: 'Building in earth: a week in Auroville',
    dest: 'Auroville',
    read: '9 min',
    hue: 'dusk',
    author: 'Lucas Bernard',
    date: 'February 2026',
    excerpt: 'Notes from a community where the walls are pressed from the soil they stand on.',
    body: [
      'There is a workshop in Auroville called the Earth Institute. It teaches people to build houses out of the ground beneath their feet. Not metaphorically — literally. You take the soil from a metre below the topsoil, mix it with a small percentage of lime, press it in a hand-operated machine into a block the size of a brick, stack it in the sun for a week, and you have a wall material that is stronger than concrete and a fraction of the carbon.',
      'I spent a week there because Indigo Lodge — where I was staying — is built entirely from compressed earth blocks made on-site. The lodge is twelve cabins arranged around a meditation pavilion. The walls breathe. The interior temperature drops fifteen degrees below the ambient mid-afternoon heat without a single air conditioner.',
      'What surprised me was the *colour*. Compressed earth varies by region — Auroville\'s soil is iron-red, the blocks are the colour of well-fired terracotta, the walls have a soft warmth that no concrete render can imitate. The morning sun on the courtyard wall is the first thing I remember about the place.',
      'The architecture is also slower. A concrete-block wall goes up in a day. An earth wall, properly cured, takes a week. The lodge\'s builder told me this is the point. "We are not in a hurry," he said. "The walls last two hundred years. A week is nothing."',
      'There is a deeper argument here about what infrastructure is *for*. If we build for a hundred years instead of twenty, the maths of construction changes entirely. The earth costs nothing. The labour is local. The product is recyclable — at the end of life, a compressed-earth block reverts to topsoil.',
      'I came back from Auroville convinced that the most interesting question in Indian architecture right now is not how to build *more* but how to build *slower*. The two are related but not the same.',
    ],
  },
  {
    slug: 'jaisalmer-fort',
    title: 'Sleeping inside a living fort',
    dest: 'Jaisalmer',
    read: '7 min',
    hue: 'sand',
    author: 'James Whitford',
    date: 'January 2026',
    excerpt: 'Jaisalmer Fort still has 3,000 residents inside its walls. Staying there is a different kind of trip.',
    body: [
      'Jaisalmer Fort is one of the very few living forts in the world. Most forts — Mehrangarh in Jodhpur, Amer in Jaipur — are now museums. People come in the morning, look around, leave. Jaisalmer Fort is a town. Three thousand people live inside its walls. Children walk to school through the bastions; the temple bell at five in the morning is for them, not for you.',
      'You stay in one of the small guesthouses that are tucked into the fort\'s lanes. Silk Route Inn is six rooms; the family who runs it has been doing so for three generations. The walls are honey-coloured sandstone, the floors are polished red oxide, the bedlinen is khadi and slightly too thin in January.',
      'The day shape in Jaisalmer is upside down from most of Rajasthan. You leave the room at six and walk the empty ramparts before the day-trippers arrive at nine. You return for breakfast and the courtyard is full of light and conversation. Mid-day you stay inside — the desert sun is patient and serious. Late afternoon you walk to a Jain temple inside the fort that has fewer visitors than the famous ones outside and is, square inch for square inch, the most carved object I have ever seen.',
      'Evening on the rooftop is what you came for. The fort sits on a hill above the city; the sandstone is gold for ten minutes and then ember for ten more. The wind picks up around sunset, the temperature drops, and the air smells faintly of cardamom from the spice shop in the lane below.',
      'A note on conservation. The fort is suffering. The walls are not designed to absorb the volume of water that modern plumbing leaks into them every day. There is an active effort — the Jaisalmer in Jeopardy fund — to restore the worst-affected bastions and to retrofit the drainage. Stay inside the fort if you want to support that work. Stay outside the fort if you want the fort to last longer. There is no right answer; both arguments are good ones.',
    ],
  },
  {
    slug: 'munnar-mornings',
    title: 'Tea, mist, and the long view',
    dest: 'Munnar',
    read: '5 min',
    hue: 'forest',
    author: 'Devika Nair',
    date: 'December 2025',
    excerpt: 'A short essay on what tea estates do to your sense of time.',
    body: [
      'A working tea estate is a place where time runs slower than it does anywhere else I have been. The plants are pruned to a precise hip-height. The pluckers move down the rows in unhurried diagonal lines. The mist comes in from the higher slopes at about 6:30 a.m. and burns off at 8:15 a.m., almost exactly, every day. There is nothing about a tea estate that wants you to be in a hurry.',
      'Postcard from Munnar is twelve cabins on a ridge above a working estate. The cabins are small and dark and well insulated against the highland chill. Each has a single window that frames the slope below.',
      'You arrive at lunchtime; the staff bring you tea that was on the plant two days ago and dried at the factory at the bottom of the road. The taste is greener and sharper than any tea you have had outside Asia. They explain — politely, often — that the tea you buy in supermarkets at home is what is *not* good enough to drink in Munnar.',
      'At dawn you wake up because the mist has thickened so much that the window is white. You make coffee — there is no kettle, you boil water on a small camp stove on the verandah — and watch the mist rearrange itself around the cabin. By 8:15 it is gone and the slope below has reappeared, freshly drawn.',
      'You will not get anything done. That is the entire point.',
    ],
  },
];

export const FAQ_GROUPS = [
  {
    title: 'Booking',
    items: [
      { q: 'How do I make a booking?', a: 'Find a stay through Explore or the home page search, choose dates and a room, and click Reserve. You\'ll be walked through a three-step wizard — guest details, payment, confirmation. You won\'t be charged until the confirmation step.' },
      { q: 'Can I book more than one room at a time?', a: 'For now, one room per booking. If you need multiple rooms in the same property for the same dates, place separate bookings — they\'ll all show up under one customer profile.' },
      { q: 'What\'s your cancellation policy?', a: 'Free cancellation up to 48 hours before check-in. Within 48 hours, the first night is charged. After check-in, no refund — but the host can sometimes offer a credit toward a future stay; ask the property directly.' },
      { q: 'Why was my booking rejected with "Room is already booked"?', a: 'Two people tried to book the same room for overlapping dates and the other person finalised first. Pick different dates or a different room.' },
    ],
  },
  {
    title: 'Account',
    items: [
      { q: 'I forgot my password.', a: 'Password reset isn\'t live yet. Sign in with Google instead, or contact us through the Contact page to get it manually reset.' },
      { q: 'Can I have both a customer and a host account?', a: 'Yes — they live in separate tables, so you can register both using the same email. Use the role toggle on the Sign in screen to pick which one to log into.' },
      { q: 'How do I delete my account?', a: 'Email contact@nestoria.example with the subject "Delete my account" and we\'ll take care of it within seven days.' },
    ],
  },
  {
    title: 'Payments',
    items: [
      { q: 'What payment methods do you accept?', a: 'Cards (Visa, Mastercard, RuPay), UPI, and pay-at-hotel for properties that allow it. The choice is on Step 2 of the booking wizard.' },
      { q: 'Why are taxes 18%?', a: 'That\'s the GST rate on hotel rooms in India for stays above ₹7,500/night. Below that threshold the rate is 12%. We display the rate that applies to your selected room.' },
      { q: 'When does the host actually get paid?', a: 'Hosts are paid monthly, on the 1st, for all completed stays in the previous calendar month — net of refunds and our 10% platform fee.' },
    ],
  },
  {
    title: 'Hosting',
    items: [
      { q: 'How do I list a property?', a: 'Sign up as a host on the Sign in screen → role toggle: I\'m hosting. Once you\'re in, the Host workspace will walk you through a three-step wizard: property basics, address + amenities, and rooms.' },
      { q: 'What kind of properties do you accept?', a: 'Independent, characterful stays in India — restored heritage homes, plantation bungalows, beach houses, small boutique hotels (under 20 rooms). We don\'t list chain hotels.' },
      { q: 'What\'s your commission?', a: '10% of the gross booking total. No listing fee, no per-stay flat fee, no surge pricing nonsense.' },
    ],
  },
];
